export const searchProfile = {
  targetRoles: [
    "technical support",
    "support analyst",
    "support specialist",
    "support engineer",
    "application support",
    "product support",
    "software support",
    "customer support engineer",
    "it support",
    "it analyst",
    "analista de suporte",
    "analista de ti",
    "analista de sistemas",
    "analista de infraestrutura",
    "analista de implantação",
    "implementation analyst",
    "implementation specialist",
    "customer onboarding",
    "technical customer success",
    "it operations",
    "noc analyst",
    "monitoring analyst",
    "observability analyst",
    "data analyst",
    "bi analyst"
  ],

  skills: [
    "sql",
    "postgresql",
    "linux",
    "windows",
    "windows server",
    "active directory",
    "rest api",
    "restful api",
    "api",
    "postman",
    "zabbix",
    "grafana",
    "javascript",
    "typescript",
    "node.js",
    "nodejs",
    "react",
    "next.js",
    "git",
    "github",
    "network",
    "networking",
    "tcp/ip",
    "troubleshooting",
    "technical support",
    "customer support",
    "incident management",
    "service desk",
    "saas"
  ],

  acceptedLocations: [
    "worldwide",
    "anywhere",
    "global",
    "brazil",
    "brasil",
    "latin america",
    "latam",
    "south america",
    "americas"
  ],

  // Esses termos normalmente indicam vagas fora do momento profissional que queremos buscar.
  excludedTitles: [
    "intern",
    "internship",
    "estágio",
    "estagiário",
    "trainee",
    "director",
    "diretor",
    "head of",
    "vice president",
    "vp ",
    "principal engineer",
    "staff engineer"
  ]
}